name: actflutterapp
description: This is a simple for Clean Architecture using the BLOC Pattern

publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.1.1+1084

environment:
  sdk: ">=2.19.6 <3.0.0"
  flutter: ">=2.0.0"

# If override conflict depends library version
#dependency_overrides:

dependencies:
  flutter:
    sdk: flutter

  # For data class
  equatable: ^2.0.5

  # Resource localizations
  flutter_localizations:
    sdk: flutter

  # Default icon for widget
  cupertino_icons: ^1.0.3

  # Support for design
  flutter_svg: 2.0.3

  # Image Cached
  cached_network_image: ^3.2.3

  # Router
  auto_route: ^5.0.4

  intl: ^0.18.0

  # dependency injection
  get_it: ^7.6.0
  injectable: ^2.1.1
  rxdart: ^0.27.2

  # state management
  flutter_bloc: 8.0.1

  # database
  hive: ^2.2.0
  hive_flutter: ^1.1.0

  # For Design Pattern
  flutter_hooks: ^0.18.1
  hooked_bloc: ^1.4.1

  # Json serializable & model
  json_annotation: ^4.8.0
  freezed: ^2.1.1
  freezed_annotation: ^2.0.3
  enum_to_string: ^2.0.1
  smooth_page_indicator: ^1.1.0

  dropdown_button2: ^2.3.7
  lottie: ^2.3.1

  # Lib for custom view
  carousel_slider: ^4.2.1
  pin_code_fields: ^7.4.0
  dotted_dashed_line: ^0.0.3
  camera: ^0.10.5+2
  cross_file_image: ^1.0.0
  fluttertoast: ^8.2.2
  dotted_border: ^2.0.0+3
  webview_flutter: ^4.2.2
  flutter_image_compress: ^2.0.4
  buttons_tabbar: ^1.3.6

  # Timer
  timer_count_down: ^2.2.0

  #select date range
  syncfusion_flutter_datepicker: ^21.2.10

  jiffy: ^6.2.1
  # A Flutter plugin that provides a Google Maps widget
  google_maps_flutter: ^2.2.6
  google_maps_flutter_android: '>=2.4.15'
  #  Google Maps autocomplete place search suggestions
  google_places_flutter: ^2.0.5
  #  provides easy geocoding and reverse-geocoding features
  geocoding: ^2.1.0
  # provides easy access to platform specific location services
  geolocator: ^10.0.0
  # opening iOS and Android phone settings
  app_settings: 4.2.0
  info_popup: ^3.0.4
  # in-app notification
  overlay_support: ^2.1.0

  # visibility detector
  visibility_detector: ^0.4.0+2

  url_launcher: ^6.1.12
  gradient_borders: ^1.0.0

  #contact read
  contacts_service: ^0.6.3

  #share
  share_plus: ^7.1.0

  #play mp4 video from server, different with youtube player
  video_player: ^2.7.2

  data:
    path: ./module/data

  domain:
    path: ./module/domain

  remote:
    path: ./module/remote

  shared:
    path: ./module/shared

  upi_pay:
    path: ./plugin/upi_pay

  flutter_upshot_plugin:
    path: ./plugin/upshot

  wifi_analyzer:
    path: ./plugin/wifi_analyzer

  file_picker: ^5.3.1
  image_picker: ^0.8.7+5
  scroll_snap_list: ^0.9.1
  qr_code_scanner: ^1.0.1
  qr_code_utils: ^0.0.1
  firebase_core: ^2.15.0
  firebase_analytics: ^10.4.4
  firebase_crashlytics: ^3.3.4
  firebase_remote_config: ^4.2.5
  hyperkyc_flutter: ^0.12.0
  collection: ^1.17.1
  permission_handler: ^11.0.0
  # discover network connectivity
  connectivity_plus: ^4.0.2

  fl_chart: ^0.63.0
  flutter_local_notifications: ^15.1.1
  flutter_timezone: ^1.0.7
  provider: ^6.0.5
  chewie: ^1.7.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  injectable_generator: ^2.1.5

  # Auto generate some files
  build_runner: ^2.3.3

  flutter_gen_runner: ^5.2.0
  json_serializable: ^6.7.0

  bloc_test: 9.0.3

  # Lint when build
  flutter_lints: ^2.0.1

  # auto route
  auto_route_generator: ^5.0.3

  flutter_launcher_icons: ^0.12.0

# Config generate when build
flutter_gen:
  output: lib/gen/
  line_length: 160
  null_safety: true

  integrations:
    flutter_svg: true
    flare_flutter: true
    lottie: true
  assets:
    enabled: true

  fonts:
    enabled: true

  colors:
    enabled: true
    inputs:
      - assets/color/colors.xml

flutter:
  uses-material-design: true
  #  generate: true
  assets:
    - assets/images/
    - assets/images/icons/
    - assets/lottie/
    - assets/images/background/
    - assets/images/navi_icons/
    - assets/map_style/

  fonts:
    - family: HankenGrotesk
      fonts:
        - asset: assets/fonts/HankenGrotesk-Bold.ttf
          weight: 700
        - asset: assets/fonts/HankenGrotesk-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/HankenGrotesk-Medium.ttf
          weight: 500
        - asset: assets/fonts/HankenGrotesk-Regular.ttf
          weight: 400

    - family: Jost
      fonts:
        - asset: assets/fonts/Jost-Bold.ttf
          weight: 700
        - asset: assets/fonts/Jost-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Jost-Medium.ttf
          weight: 500
        - asset: assets/fonts/HankenGrotesk-Regular.ttf
          weight: 400

    - family: Manrope
      fonts:
        - asset: assets/fonts/manrope.bold.otf
          weight: 700
        - asset: assets/fonts/manrope.semibold.otf
          weight: 600
        - asset: assets/fonts/manrope.medium.otf
          weight: 500
        - asset: assets/fonts/manrope.regular.otf
          weight: 400

flutter_intl:
  enabled: true
  class_name: LanguageTranslation
  main_locale: en
